import { CLIENT_ID_ANDROID, CLIENT_ID_IOS, API_KEY, AUTH_DOMAIN, PROJECT_ID, STORAGE_BUCKET, MESSAGING_SENDER_ID, APP_ID  } from '@env';

export default {
    CLIENT_ID_ANDROID,
    CLIENT_ID_IOS,
    API_KEY,
    AUTH_DOMAIN,
    PROJECT_ID,
    STORAGE_BUCKET,
    MESSAGING_SENDER_ID,
    APP_ID
}